// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Rdistance
Rcpp::List Rdistance(std::string w2vFilename, std::string targetWord, int nword);
RcppExport SEXP Rword2vec_Rdistance(SEXP w2vFilenameSEXP, SEXP targetWordSEXP, SEXP nwordSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type w2vFilename(w2vFilenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type targetWord(targetWordSEXP);
    Rcpp::traits::input_parameter< int >::type nword(nwordSEXP);
    __result = Rcpp::wrap(Rdistance(w2vFilename, targetWord, nword));
    return __result;
END_RCPP
}
// Rword2vec
int Rword2vec(std::string Rtrain_file, std::string Routput_file, std::string Rsave_vocab_file, std::string Rread_vocab_file, int Rlayer1_size, int Rbinary, int Rcbow, int Ralpha, int Rwindow, int Rhs, int Rsample, int Rnegative, int Rnum_threads, int Riter, int Rmin_count, int Rclasses);
RcppExport SEXP Rword2vec_Rword2vec(SEXP Rtrain_fileSEXP, SEXP Routput_fileSEXP, SEXP Rsave_vocab_fileSEXP, SEXP Rread_vocab_fileSEXP, SEXP Rlayer1_sizeSEXP, SEXP RbinarySEXP, SEXP RcbowSEXP, SEXP RalphaSEXP, SEXP RwindowSEXP, SEXP RhsSEXP, SEXP RsampleSEXP, SEXP RnegativeSEXP, SEXP Rnum_threadsSEXP, SEXP RiterSEXP, SEXP Rmin_countSEXP, SEXP RclassesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type Rtrain_file(Rtrain_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type Routput_file(Routput_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type Rsave_vocab_file(Rsave_vocab_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type Rread_vocab_file(Rread_vocab_fileSEXP);
    Rcpp::traits::input_parameter< int >::type Rlayer1_size(Rlayer1_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type Rbinary(RbinarySEXP);
    Rcpp::traits::input_parameter< int >::type Rcbow(RcbowSEXP);
    Rcpp::traits::input_parameter< int >::type Ralpha(RalphaSEXP);
    Rcpp::traits::input_parameter< int >::type Rwindow(RwindowSEXP);
    Rcpp::traits::input_parameter< int >::type Rhs(RhsSEXP);
    Rcpp::traits::input_parameter< int >::type Rsample(RsampleSEXP);
    Rcpp::traits::input_parameter< int >::type Rnegative(RnegativeSEXP);
    Rcpp::traits::input_parameter< int >::type Rnum_threads(Rnum_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type Riter(RiterSEXP);
    Rcpp::traits::input_parameter< int >::type Rmin_count(Rmin_countSEXP);
    Rcpp::traits::input_parameter< int >::type Rclasses(RclassesSEXP);
    __result = Rcpp::wrap(Rword2vec(Rtrain_file, Routput_file, Rsave_vocab_file, Rread_vocab_file, Rlayer1_size, Rbinary, Rcbow, Ralpha, Rwindow, Rhs, Rsample, Rnegative, Rnum_threads, Riter, Rmin_count, Rclasses));
    return __result;
END_RCPP
}
