# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rdistance <- function(w2vFilename, targetWord, nword) {
    .Call('Rword2vec_Rdistance', PACKAGE = 'Rword2vec', w2vFilename, targetWord, nword)
}

Rword2vec <- function(Rtrain_file, Routput_file, Rsave_vocab_file, Rread_vocab_file, Rlayer1_size, Rbinary, Rcbow, Ralpha, Rwindow, Rhs, Rsample, Rnegative, Rnum_threads, Riter, Rmin_count, Rclasses) {
    .Call('Rword2vec_Rword2vec', PACKAGE = 'Rword2vec', Rtrain_file, Routput_file, Rsave_vocab_file, Rread_vocab_file, Rlayer1_size, Rbinary, Rcbow, Ralpha, Rwindow, Rhs, Rsample, Rnegative, Rnum_threads, Riter, Rmin_count, Rclasses)
}

